
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600
  config.vm.box = "ubuntu/bionic64"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3065"
  end

  config.vm.provision :docker

  config.vm.define "server-1" do |ci|
    ci.vm.network "private_network", ip: "192.168.56.60"
    ci.vm.hostname = "ci-server"
    ci.vm.provision :file, source: "../docker/docker-compose.ci.yaml", destination: "docker-compose.yml"
    ci.vm.provision :docker_compose, yml: "/home/vagrant/docker-compose.yml", run: "always"
    ci.vm.provision :shell, inline: "sudo chmod 777 /var/run/docker.sock"
  end
end
